### ISSUE TITLE
SV refinement subfamilies Other_SVA_F

### ISSUE THREAD

**Issue by Zoeyoungxy** [parklab/SVA_landscape_project#1]
Hi,
Thank you for carrying out such a great SVA annotation refinement module. I've noticed that the Annotated subfamily of the SVA 'Other_SVA_F'. Would you please provide some detailed information on this type? I wonder the difference between the type 'Other_SVA_F' and common SVA_F. 
BTW, the number of SVAs was reduced a lot after refinement, is it normal?

Any suggestions will be highly appreciated.
Thanks!
-Zoey

**Comment by simoncchu** [comment]
Hi sorry for the late response. Somehow missed this notification in email.

"Other_SVA_F" is mainly those uncertain ones. For example, sometimes, one SVA will be annotated to more than one subfamily in RepeatMasker output. 

If your input is the reference annotation, most of the time you will have a smaller size of refined annotation, because in many cases one SVA will be annotated to several records in RepeatMasker output. 

I hope it helps.

**Comment by Zoeyoungxy** [comment]
> Hi sorry for the late response. Somehow missed this notification in email.
> 
> "Other_SVA_F" is mainly those uncertain ones. For example, sometimes, one SVA will be annotated to more than one subfamily in RepeatMasker output.
> 
> If your input is the reference annotation, most of the time you will have a smaller size of refined annotation, because in many cases one SVA will be annotated to several records in RepeatMasker output.
> 
> I hope it helps.

This really helps me a lot. Thank You!
